import random
from faker import Faker

greetings = ["Hello", "Hi", "Hey", "Howdy", "Hola"]
colors = ["Red", "Black", "Green"]


# deck = list(range(1, 53))
# results = random.choices(colors, weights=[10, 1, 60], k=30)
# value = random.choice(greetings)
# print(f"{value}, Felipe Alves!")
# print(results)
# random.shuffle(deck)
# hand = random.sample(deck, k=10)
# print(hand)

first_name = [
    "Zachary",
    "Brenda",
    "Amber",
    "Samantha",
    "Kristen",
    "Timothy",
    "Michelle",
    "Kyle",
    "Jessica",
    "James",
    "Henry",
    "Timothy",
    "Scott",
    "Jessica",
    "Rebecca",
    "Lauren",
    "Rebekah",
    "Elizabeth",
    "Kevin",
    "Maria",
    "Brian",
    "Matthew",
    "Elizabeth",
    "Kevin",
    "Sherry",
    "Maria",
    "Krista",
    "Teresa",
    "Gregory",
    "Kayla",
    "Alexander",
    "Julie",
    "David",
    "Amy",
    "Jeffrey",
    "Marvin",
    "Donna",
    "Mckenzie",
    "Julia",
    "Kimberly",
    "Donna",
    "Kyle",
    "Cassandra",
    "Kenneth",
    "Donna",
    "Sarah",
    "Tammy",
    "Renee",
    "Alexis",
    "Justin",
    "Larry",
]
last_name = [
    "Freeman",
    "Wilson",
    "Thomas",
    "Nicholson",
    "Johnson",
    "Roach",
    "King",
    "Lopez",
    "Cook",
    "Robertson",
    "Benitez",
    "Burns",
    "Howard",
    "Anthony",
    "Gutierrez",
    "Hogan",
    "Moore",
    "Carter",
    "Hunter",
    "Cisneros",
    "Anderson",
    "Gonzales",
    "Green",
    "Jones",
    "Mitchell",
    "Pham",
    "Mills",
    "Gonzalez",
    "Price",
    "Mcconnell",
    "Howe",
    "Hughes",
    "Sims",
    "Glenn",
    "Soto",
    "Mejia",
    "Clark",
    "Smith",
    "Hernandez",
    "Page",
    "Black",
    "Fisher",
    "Garrison",
    "King",
    "Stanley",
    "Ferguson",
    "Howell",
    "Gomez",
    "West",
    "Moore",
    "Palmer",
]
street_name = [
    "Station",
    "Curve",
    "Mountains",
    "Landing",
    "Orchard",
    "Dale",
    "Hills",
    "Rest",
    "Point",
    "Fall",
    "Tunnel",
    "Spurs",
    "Courts",
    "Ranch",
    "Causeway",
    "Park",
    "River",
    "Shores",
    "Manor",
    "Pike",
    "Corner",
    "Trail",
    "Rapid",
    "Flats",
    "Trace",
    "Ville",
    "Square",
    "Shoals",
    "Passage",
    "Circle",
    "Mount",
    "Forest",
    "Canyon",
    "Harbor",
    "Circles",
    "Unions",
    "Mountains",
    "Mount",
    "Trafficway",
    "View",
    "Burgs",
    "Mount",
    "Forest",
    "Ridge",
    "View",
    "Courts",
    "Crossroad",
    "Stream",
    "Port",
    "Land",
    "Vista",
]
city_name = [
    "Grantton",
    "Eileenchester",
    "Port Alexanderfort",
    "East Johnstad",
    "East Jill",
    "Connieshire",
    "Mosleyfort",
    "Stephensside",
    "South Joshuafort",
    "East Edward",
    "New Jenniferstad",
    "Luketown",
    "Henryfurt",
    "West Mariaside",
    "Emilyland",
    "Taylorland",
    "Josephberg",
    "Port Michelle",
    "Gordonton",
    "Andreshire",
    "Paynehaven",
    "Martinezberg",
    "Port Jennifer",
    "North Keithchester",
    "Lake Robert",
    "North William",
    "New Christopher",
    "New Phillip",
    "South Calvin",
    "South William",
    "Lake Crystal",
    "Kylemouth",
    "Edwardchester",
    "Lake Craigside",
    "Burnsmouth",
    "Kimton",
    "Lake Jacqueline",
    "Johnside",
    "Nicolehaven",
    "Lake Tammy",
    "Port Colleen",
    "New Janiceberg",
    "East Brianville",
    "Kyleshire",
    "West Leslietown",
    "South Dan",
    "New Teresa",
    "West Caitlinfurt",
    "Lake Dawn",
    "West Michelle",
    "Lake Linda",
]
codestates_name = [
    "KE",
    "LI",
    "BT",
    "NZ",
    "LV",
    "CN",
    "TL",
    "MD",
    "KW",
    "MA",
    "EE",
    "BG",
    "HT",
    "KG",
    "ME",
    "CU",
    "PL",
    "MV",
    "VU",
    "BS",
    "OM",
    "GE",
    "RO",
    "FR",
    "GE",
    "LI",
    "QA",
    "MK",
    "BG",
    "MW",
    "ML",
    "TT",
    "FJ",
    "US",
    "PL",
    "UG",
    "DE",
    "WS",
    "SO",
    "SR",
    "DK",
    "RW",
    "ZW",
    "CU",
    "GA",
    "AZ",
    "FJ",
    "KH",
    "NA",
    "BD",
    "SO",
]
email_adressess = ["outlook.com", "live.com", "hotmail.com", "gmail.com", "yahoo.com"]
for num in range(100):
    first = random.choice(first_name)
    last = random.choice(last_name)

    phone = f"{random.randint(100, 999)}-555-{random.randint(1000, 9999)}"

    street_num = random.randint(100, 999)
    street = random.choice(street_name)
    city = random.choice(city_name)
    state = random.choice(codestates_name)
    zip_code = random.randint(10000, 99999)
    adress = f"{street_num} {last} St., {city} {state} {zip_code}"

    ad = random.choice(email_adressess)
    email = first.lower() + last.lower() + "@" + ad.lower()

    print(f"{first} {last}\n{phone}\n{adress}\n{email}\n")

